[package]
name = "backends"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
futures-util = "0.3.31"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
tokio-tungstenite = "0.24.0"
